### ISSUE TITLE
cmake can't find armclang at build time

### ISSUE THREAD

**Issue by HalfSweet** [Open-CMSIS-Pack/cbuild#142]
In https://github.com/ARM-software/vscode-keil-studio-pack/issues/8 I found a very similar problem to the one I encountered. 
When building with cbuild, cmake complains that `CMAKE_C_COMPILER` and `CMAKE_AS_ARM_COMPILER` are not found. This is reproduced under both windows 11 and Ubuntu 22.04, and whether using VSCode's integrated tools or the command line

cbuild version: `cbuild version 2.2.1 (C) 2023 Arm Ltd. and Contributors`

**Comment by HalfSweet** [comment]
Resolved in https://github.com/ARM-software/vscode-keil-studio-pack/issues/8, doesn't seem to have anything to do with cbuild :(

**Comment by jkrech** [comment]
Sorry for the lack of response here.
It turns out that the toolchain registration variable `AC6_TOOLCHAIN_6_21_0` was pointing to a directory that does not exist and therefore cmake could not find the compiler.
Maybe that is something that `csoultion` could catch early on. At the same time the environment variable could point to a directory that exists but does not contain the toolchain binaries but `csolution` does not know anything about the toolchain binaries. Therefore in my opinion this check really belongs to Cmake.
